### ISSUE TITLE
Not working with material-ui v1

### ISSUE THREAD

**Issue by jvadillo** [ukatama/material-ui-skeleton#5]
The following error happens using material-ui v1:

./~/material-ui-search-bar/lib/components/SearchBar/SearchBar.js
Module not found: Can't resolve 'material-ui/AutoComplete' in 'C:\Users\vadil\Documents\dev\reactjs\react-material-ui\node_modules\material-ui-search-bar\lib\components\SearchBar'

¿Are you thinking about updating the component to material-ui v1?

**Comment by esnya** [comment]
It does not seem to be an error of this project.
And I will not maintain this project. I will only merge PR.
